Display report status changes and their motivations on report page
globaleaks/GlobaLeaks pull request #4117
Opened 2024-06-24 14:28 UTC by evilaliv3

Implement feature #4115

- [ ] The pull request should include a description of the problem you're trying to solve
- [ ] The pull request should include overview of the suggested solution
- [ ] If the pull requests changes current behavior, reasons why your solution is better.
- [ ] The proposed code should be fully functional
- [ ] The proposed code should contain tests relevant to prove is functionality
- [ ] The proposed tests should ensure significative code coverage
- [ ] All new and existing tests should pass

2024-07-03 03:05 UTC, devops-itsware commented on backend/globaleaks/models/serializers.py
> +def get_label(session, label_id, table):
This function is not being used anywhere. Consider removing it and adding when needed.

2024-07-03 03:06 UTC, obinnaeye commented on backend/globaleaks/models/serializers.py
> +def get_label(session, label_id, table):
This function is not being used anywhere. Consider removing it and adding when needed.

2024-07-03 03:14 UTC, obinnaeye commented on backend/globaleaks/models/serializers.py
> +def process_logs(session, tip ,tip_id):
Minor one: should be `def process_logs(session, tip, tip_id):`. We might need to run a linter to ensure a clean code.

2024-07-03 03:17 UTC, obinnaeye commented on backend/globaleaks/models/serializers.py
> +    logs = get_audit_log(session,tip_id)
Missing whitespace after ','
Should be `logs = get_audit_log(session, tip_id)`
As mentioned above, consider linting.

2024-07-03 03:18 UTC, obinnaeye commented on client/app/src/models/app/shared-public-model.ts
> +  data: any;
Avoid `any` data type.

2024-07-03 03:25 UTC, obinnaeye commented on client/app/src/models/app/shared-public-model.ts
> +  type: string;
Looks like `type` in this case is better an `enum` than a `string`. This way, there'll be consistency.

2024-07-03 03:27 UTC, obinnaeye commented on backend/globaleaks/models/serializers.py
> +from datetime import datetime
Redundant import can be removed.

2024-07-03 03:28 UTC, obinnaeye commented on backend/globaleaks/handlers/recipient/rtip.py
> +        tip = yield serializers.process_logs(tip,tip['id'])
No whitespace after ","
Consider linting.

2024-07-03 04:02 UTC, obinnaeye commented on backend/globaleaks/models/serializers.py
> +    }
I'm not sure the type of `log`, but if it is `auditlogResolverModel` in `client/app/src/models/resolvers/auditlog-resolver-model.ts`, `user_id` and `object_id` are optional and might be `undefined`. This works well, but could introduce a potential bug downstream.

2024-07-03 07:06 UTC, frasercrichton requested changes
There should be tests that go along with any change to document the change and verify it's functionality. Ideally these should be unit tests as integration tests are notoriously flaky.

2024-07-03 10:51 UTC, obinnaeye commented on client/app/src/shared/partials/tip-comments/tip-comments.component.html
> +                    <div class="message">
Since `comment.author_id` is referenced within this div, is this change not going to break anything?

2024-07-03 11:49 UTC, obinnaeye commented
I tried (manually) testing this locally but couldn't figure out how to test the feature implemented; I'm new to Globaleaks codebase.
Can you add some test steps for local manual testing?  

Also, the pull request doesn't follow the pull request template here https://github.com/globaleaks/GlobaLeaks/blob/main/.github/PULL_REQUEST_TEMPLATE.md.

2024-08-12 16:40 UTC, evilaliv3 commented
Closing as manually merged into devel branch

2024-08-12 16:40 UTC, closed without merging